### ISSUE TITLE
Não é possível baixar todos os dados de candidatos para vereador para eleção de 2000

### ISSUE THREAD

**Issue by fredpolicarpo** [Cepesp-Fgv/cepesp-rest#10]
Quando tento baixar todos os dados na categoria **candidatos**, no ano de **2000** e cargo **vereador**

Está baixando um arquivo vazio, com o seguinte conteúdo:

> No columns to parse from file

A requisição é a seguinte:

`http://cepesp.io/api/consulta/candidatos?format=csv&ano=2000&cargo=13&selected_columns[]=DATA_GERACAO&selected_columns[]=ANO_ELEICAO&selected_columns[]=NUM_TURNO&selected_columns[]=DESCRICAO_ELEICAO&selected_columns[]=SIGLA_UF&selected_columns[]=DESCRICAO_UE&selected_columns[]=CODIGO_CARGO&selected_columns[]=DESCRICAO_CARGO&selected_columns[]=NOME_CANDIDATO&selected_columns[]=NUMERO_CANDIDATO&selected_columns[]=CPF_CANDIDATO&selected_columns[]=NOME_URNA_CANDIDATO&selected_columns[]=COD_SITUACAO_CANDIDATURA&selected_columns[]=DES_SITUACAO_CANDIDATURA&selected_columns[]=NUMERO_PARTIDO&selected_columns[]=SIGLA_PARTIDO&selected_columns[]=NOME_PARTIDO&selected_columns[]=CODIGO_LEGENDA&selected_columns[]=SIGLA_LEGENDA&selected_columns[]=COMPOSICAO_LEGENDA&selected_columns[]=NOME_COLIGACAO&selected_columns[]=CODIGO_OCUPACAO&selected_columns[]=DESCRICAO_OCUPACAO&selected_columns[]=DATA_NASCIMENTO&selected_columns[]=NUM_TITULO_ELEITORAL_CANDIDATO&selected_columns[]=IDADE_DATA_ELEICAO&selected_columns[]=CODIGO_SEXO&selected_columns[]=DESCRICAO_SEXO&selected_columns[]=COD_GRAU_INSTRUCAO&selected_columns[]=DESCRICAO_GRAU_INSTRUCAO&selected_columns[]=CODIGO_ESTADO_CIVIL&selected_columns[]=DESCRICAO_ESTADO_CIVIL&selected_columns[]=CODIGO_NACIONALIDADE&selected_columns[]=DESCRICAO_NACIONALIDADE&selected_columns[]=SIGLA_UF_NASCIMENTO&selected_columns[]=CODIGO_MUNICIPIO_NASCIMENTO&selected_columns[]=NOME_MUNICIPIO_NASCIMENTO&selected_columns[]=DESPESA_MAX_CAMPANHA&selected_columns[]=COD_SIT_TOT_TURNO&selected_columns[]=DESC_SIT_TOT_TURNO`

Essa mesma requisição funciona para todos os outros cargos em todas as eleições.

**Comment by Cepesp-Fgv** [comment]
Problema resolvido.

**Comment by fredpolicarpo** [comment]
O problema presiste
