### ISSUE TITLE
Dados não normalizados para tabela candidatos a prefeito coluna descricao_ue Goiânia/GO

### ISSUE THREAD

**Issue by fredpolicarpo** [Cepesp-Fgv/cepesp-rest#11]
Para candidatos a prefeito da cidade de Goiânia/GO
Em alguns registros temos **descricao_ue**=*GOIANIA* (Sem acento)
Em outros registros temos **descricao_ue**=*GOIÂNIA* (Com acento)

**Comment by Cepesp-Fgv** [comment]
Fred 
Obrigado pelo issue.
De fato não está padronizado os nomes dos municípios nos diferentes anos da base de candidatos. Este é um problema que existe e estamos cientes e ele vem diretamente do TSE que registra mesmos municípios com grafias diferentes em diferentes anos. Em breve procuraremos ter uma consistência de nomenclatura. Por enquanto sugerimos utilizar a variável sigla_ue (que é numérica e consistente ao longo dos anos).
Obrigado
Equipe CEPESPData
