### ISSUE TITLE
Consulta na tabela legenda filtrando por Candidato Estadual em 2010 não está retornando dados

### ISSUE THREAD

**Issue by fredpolicarpo** [Cepesp-Fgv/cepesp-rest#13]
http://cepesp.io/api/consulta/legendas?format=csv&ano=2010&cargo=7&selected_columns[]=DATA_GERACAO&selected_columns[]=ANO_ELEICAO&selected_columns[]=NUM_TURNO&selected_columns[]=DESCRICAO_ELEICAO&selected_columns[]=SIGLA_UF&selected_columns[]=SIGLA_UE&selected_columns[]=CODIGO_CARGO&selected_columns[]=DESCRICAO_CARGO&selected_columns[]=TIPO_LEGENDA&selected_columns[]=NUMERO_PARTIDO&selected_columns[]=SIGLA_PARTIDO&selected_columns[]=NOME_PARTIDO&selected_columns[]=SIGLA_COLIGACAO&selected_columns[]=NOME_COLIGACAO&selected_columns[]=COMPOSICAO_COLIGACAO&selected_columns[]=SEQUENCIAL_COLIGACAO

**Comment by lins-morandi** [comment]
Olá @fredpolicarpo ,

A consulta às legendas indicada acima já está disponível [neste link](http://cepesp.io/consulta/legendas?cargo=7&anos%5B%5D=2010&query-table_length=10&c%5B%5D=DATA_GERACAO&c%5B%5D=HORA_GERACAO&c%5B%5D=ANO_ELEICAO&c%5B%5D=NUM_TURNO&c%5B%5D=SIGLA_UF&c%5B%5D=SIGLA_UE&c%5B%5D=CODIGO_CARGO&c%5B%5D=DESCRICAO_CARGO&c%5B%5D=TIPO_LEGENDA&c%5B%5D=NUMERO_PARTIDO&c%5B%5D=SIGLA_COLIGACAO&c%5B%5D=NOME_COLIGACAO&c%5B%5D=COMPOSICAO_COLIGACAO&c%5B%5D=SEQUENCIA_COLIGACAO). O link deve funcionar normalmente para baixar os dados via API Rest também.

À disposição, Equipe Cepespdata
