### ISSUE TITLE
Consulta não está retornando o nome do município e sim o código

### ISSUE THREAD

**Issue by josircg** [Cepesp-Fgv/cepesp-rest#15]
`http://cepesp.io/api/consulta/tse?cargo=1&ano=2014&agregacao_regional=6&agregacao_politica=4`

**Comment by leonardocsantoss** [comment]
Criei o management para consultar a api e gravar no model UE.

**Comment by josircg** [comment]
Olá pessoal, acabei de fazer a consulta e o sistema retornou ainda sem o nome do município.
