### ISSUE TITLE
Diversas colunas erradas na tabela candidato para vereadores da eleição de 2000

### ISSUE THREAD

**Issue by fredpolicarpo** [Cepesp-Fgv/cepesp-rest#17]
Exemplo:
cod_grau_instrucao: "MASCULINO"

Também encontrei dados errados nas seguintes colunas, mas não anotei o dado errado:
CODIGO_OCUPACAO
COD_SITUACAO_CANDIDATURA

**Comment by Cepesp-Fgv** [comment]
Pode enviar a consulta em que o problema foi encontrado?

**Comment by lins-morandi** [comment]
Olá @fredpolicarpo ,

Várias mudanças foram implementadas no nosso site nos últimos meses. Creio que este problema tenha sido resolvido. Veja, por exemplo, esta consulta aos [candidatos a vereadores no estado do Acre](http://cepespdata.io/consulta/tse?cargo=13&agregacao_regional=6&agregacao_politica=2&anos%5B%5D=2016&uf_filter=AC&mun_filter=&query-table_length=10&c%5B%5D=ANO_ELEICAO&c%5B%5D=NUM_TURNO&c%5B%5D=COD_MUN_IBGE&c%5B%5D=NOME_MUNICIPIO&c%5B%5D=CODIGO_MESO&c%5B%5D=NOME_MESO&c%5B%5D=UF&c%5B%5D=CODIGO_MACRO&c%5B%5D=NOME_MACRO&c%5B%5D=DESCRICAO_ELEICAO&c%5B%5D=DESCRICAO_CARGO&c%5B%5D=NOME_CANDIDATO&c%5B%5D=NUMERO_CANDIDATO&c%5B%5D=CPF_CANDIDATO&c%5B%5D=DES_SITUACAO_CANDIDATURA&c%5B%5D=NUMERO_PARTIDO&c%5B%5D=SIGLA_PARTIDO&c%5B%5D=DESCRICAO_OCUPACAO&c%5B%5D=NUM_TITULO_ELEITORAL_CANDIDATO&c%5B%5D=DESCRICAO_GRAU_INSTRUCAO&c%5B%5D=DESC_SIT_TOT_TURNO&c%5B%5D=QTDE_VOTOS).

Agradecemos o comentário e não hesite em reativar este issue caso o problema se repita. 

Ficamos à disposição, Equipe Cepespdata
