### ISSUE TITLE
Internal Server Error ao solicitar dados do candidato a Deputado Federal 4565 de São Paulo 

### ISSUE THREAD

**Issue by fcereda** [Cepesp-Fgv/cepesp-rest#18]
Prezados amigos,

Encontrei um erro que aparece apenas com o candidato em 2014 a deputado federal 4565 de São Paulo. A chamada à API é:

http://cepesp.io/api/consulta/votos?cargo=6&ano=2014&agregacao_politica=1&agregacao_regional=7&columns[0][name]=NUM_TURNO&columns[0][search][value]=1&columns[1][name]=UF&columns[1][search][value]=SP&columns[2][name]=NUMERO_CANDIDATO&columns[2][search][value]=4565

O servidor responde com o código 500, Internal Server Error.

Já tentei com outros candidatos , inclusive o mais votado (número 1000) e em todos os outros casos o servidor responde sem problemas.

**Comment by Cepesp-Fgv** [comment]
A consulta foi corrigida.
