### ISSUE TITLE
2012 returns Usecols do not match names

### ISSUE THREAD

**Issue by paeselhz** [Cepesp-Fgv/cepesp-rest#2]
While trying to use the API to download data about councillors in 2012, the CSV file returned only contains a line saying Usecols do not match names. The link used to download is pasted below. I can't figure out what the problem is since all the other files from 1998 to 2016 does not show this problem.

"http://cepesp.io/api/consulta/tse?ano=2012&cargo=13&agregacao_regional=6&agregacao_politica=2&selected_columns[]=NOME_MUNICIPIO&selected_columns[]=QTDE_VOTOS&selected_columns[]=DESC_SIT_TOT_TURNO&selected_columns[]=NOME_UF&selected_columns[]=SIGLA_PARTIDO&selected_columns[]=NOME_MICRO&selected_columns[]=NUM_TURNO&selected_columns[]=COD_MUN_IBGE&selected_columns[]=ANO_ELEICAO&selected_columns[]=NOME_CANDIDATO&selected_columns[]=DESCRICAO_CARGO&selected_columns[]=NOME_MESO&selected_columns[]=COMPOSICAO_LEGENDA&selected_columns[]=NOME_URNA_CANDIDATO"

Thanks in advance,
Luis Paese

**Comment by josircg** [comment]
"Usecols do not match names" means that one of your selected_columns was invalid. To debug, remove each of them to find which is invalid.

**Comment by paeselhz** [comment]
I just find troubling that even though I don't use the selected_columns argument, the system also returns "Usecols do not match names". For example, if I try downloading the dataset from 2016, for Councillors, organized by Municipality I can download through this link:

http://cepesp.io/api/consulta/tse?ano=2016&cargo=13&agregacao_regional=6&agregacao_politica=2

But when I try the exact same link, only changing the year to 2012(http://cepesp.io/api/consulta/tse?ano=2012&cargo=13&agregacao_regional=6&agregacao_politica=2), I get the error that "Usecols do not match names"

**Comment by josircg** [comment]
I got the error here too. Probably, it halts because it will return too many data (all vereadores from 2012. Today several queries from my project stop to work too :(

**Comment by paeselhz** [comment]
It's awkward that for me only 2012 isn't working... All the other years are working fine from 1998 to 2016, through out all the dependencies, but for Vereadores in 2012, the code crashes...

**Comment by Cepesp-Fgv** [comment]
O problema da consulta se encontra na coluna DESC_SIT_TOT_TURNO. Ao remover ela da consulta, o resultado vem sem nenhum problema. De qualquer forma, estamos investigando o problema mais a fundo para que esta coluna volte a funcionar.

**Comment by paeselhz** [comment]
Existe alguma previsão para que os resultados venham com a coluna DESC_SIT_TOT_TURNO?

**Comment by lins-morandi** [comment]
Olá @paeselhz ,

Nós estamos com uma [nova API Rest](https://github.com/Cepesp-Fgv/cepesp-rest) implementada. Você consegue realizar sua resquisição de candidatos a vereadores p/ o ano de 2012 por município utilizando o link:

`cepesp.io/api/consulta/athena/query?table=tse&cargo=13&anos=2012&agregacao_regional=6&agregacao_politica=2`

De onde tiramos o id = **7285** p/ baixar a consulta: 
`cepesp.io/api/consulta/athena/result?id=7285&ignore_version=true`.

Como pode perceber no CSV baixado, a coluna **DESC_SIT_TOT_TURNO** já é default desta consulta -- não precisa nem acrescentar na sua requisição (primeiro link acima).

Espero que ajude. 

Ficamos à disposição,
Equipe Cepespdata/FGV
