### ISSUE TITLE
Data de nascimento errada para Candidatos a presidente de 1998

### ISSUE THREAD

**Issue by fredpolicarpo** [Cepesp-Fgv/cepesp-rest#4]
http://cepesp.io/consulta/candidatos?cargo=1&anos=1998&selected_columns[]=DATA_GERACAO&selected_columns[]=ANO_ELEICAO&selected_columns[]=CODIGO_CARGO&selected_columns[]=DATA_NASCIMENTO&selected_columns[]=DESC_SIT_TOT_TURNO
![cepesp data](https://user-images.githubusercontent.com/11080400/33049202-0a4454e6-ce46-11e7-97e1-cf88c6d030f9.png)

**Comment by Cepesp-Fgv** [comment]
Todos os problemas com as datas de nascimento foram resolvidos. Agora estão todas no padrão DIA/MÊS/ANO
