### ISSUE TITLE
Dado errado! IDADE_DATA_ELEICAO=MARANHÃO (Candidatos/DeputadoFederal/2010/)

### ISSUE THREAD

**Issue by fredpolicarpo** [Cepesp-Fgv/cepesp-rest#5]
Partido = PSL
UF = MA

![image](https://user-images.githubusercontent.com/11080400/33050689-5709492e-ce4d-11e7-8009-60d1d71c859a.png)

**Comment by Cepesp-Fgv** [comment]
Todos os dados do ano 2010 referente ao candidato CARLOS MAGNO foi corrigido.
