### ISSUE TITLE
Dado Errado! cod_grau_instrucao candidato/deputado federal/2010

### ISSUE THREAD

**Issue by fredpolicarpo** [Cepesp-Fgv/cepesp-rest#6]
Maranhão
NumPartido = 17

![image](https://user-images.githubusercontent.com/11080400/33051001-0baaea58-ce4f-11e7-8a1a-a3b3a72dff21.png)

**Comment by Cepesp-Fgv** [comment]
Os dados do candidato estavam mal formatados. O erro foi corrigido.
