### ISSUE TITLE
Dado errado: Despesa maxima de campanha, candidatos/deputado federal/2010

### ISSUE THREAD

**Issue by fredpolicarpo** [Cepesp-Fgv/cepesp-rest#7]
Os dados do deputado Carlos Magno estão com diversos problemas

![image](https://user-images.githubusercontent.com/11080400/33051854-1a9d7c70-ce53-11e7-9b18-38030e7cd674.png)

**Comment by Cepesp-Fgv** [comment]
Fixed!
