### ISSUE TITLE
Votação para Presidente por município está com os valores duplicados

### ISSUE THREAD

**Issue by paeselhz** [Cepesp-Fgv/cepesp-rest#9]
Quando consultando os resultados eleitorais, por município, para Presidente, os valores aparecem duplicados do que consta no TSE

CEPESP Data:
![image](https://user-images.githubusercontent.com/25777539/33138546-e787b540-cf91-11e7-9ffb-67d6449429c2.png)

TSE:
![image](https://user-images.githubusercontent.com/25777539/33138397-8c776dbc-cf91-11e7-9a33-5e9ca06ef13a.png)

A demonstração está com o Município de Caxias do Sul/RS, mas esse erro consta em todos os municípios do país

**Comment by Cepesp-Fgv** [comment]
O problema ainda persiste? Se sim, pode nos enviar um link para a consulta? Pois não conseguimos simular o problema.

**Comment by paeselhz** [comment]
Sim, o problema ainda insiste. Esse resultado pode ser encontrado no link http://cepesp.io/consulta/tse?cargo=1&agregacao_regional=6&agregacao_politica=2&anos%5B%5D=2010&uf_filter=RS&mun_filter= , com o filtro de município configurado para Caxias do Sul e o número do turno configurado para 1 (NUM_TURNO == 1).

**Comment by lins-morandi** [comment]
Olá, @paeselhz ,

Acabo de testar a consulta indicada acima e o problema parece estar resolvido (veja na captura de tela do csv que baixei a partir do link que você enviou, filtrado p/ Caxias do Sul).

![Screenshot from 2019-07-12 21-30-47](https://user-images.githubusercontent.com/47109522/61164522-637ec400-a4ec-11e9-8481-7c533eb4e61f.png)


Não hesite em reabrir o issue caso ele se repita. Obrigada pela contribuição. 
À disposição, Equipe Cepespdata
